# Generated by Django 6.0.4 on 2026-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgparecord',
            name='total_credit_points',
            field=models.FloatField(),
        ),
    ]
