# Generated by Django 6.0.4 on 2026-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cgparecord_total_credit_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgparecord',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
