# Generated by Django 6.0.4 on 2026-05-13 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cgparecord_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CGPARecord',
            new_name='OsasCGPARecord',
        ),
    ]
